server:
  port: 9129
spring:
  application:
    name: magicconfig-server
  profiles:
    active: dev
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:h2db
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magicconfig?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db.sql
      mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
logging:
  level:
    root: info
    com.switchvov.magicconfig.server: debug